name: 代码质量检查

on:
  pull_request:
    branches: ["main"]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - run: npm ci --legacy-peer-deps
      - run: npm run check-lint
      - run: npm run check-prettier
      - run: npm run check-test
      - run: npm run check-security