name: Docker Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Extract Version Tag
      run: |
        echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_REPO }}:$TAG
    - name: Conditionally Tag as Latest
      if: |
        startsWith(join(path.split(env.TAG, '-'), ''), 'b') == false
      run: |
        docker tag ${{ secrets.DOCKER_REPO }}:$TAG ${{ secrets.DOCKER_REPO }}:latest
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_REPO }}:$TAG
        if: |
          startsWith(join(path.split(env.TAG, '-'), ''), 'b') == false
        docker push ${{ secrets.DOCKER_REPO }}:latest
