name: Docker Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile --tag ${{ env.DOCKER_REPO }}:${{ github.ref }}
        docker tag ${{ env.DOCKER_REPO }}:${{ github.ref }}
    - name: Push Docker Image
      run: |
        docker push ${{ env.DOCKER_REPO }}
