name: Docker Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
    - name: Extract Version Tag
      run: |
        echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        
    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_REPO }}:$TAG
        
    - name: Conditionally Tag as Latest
      if: |
          !endsWith(env.TAG, 'b')
      run: |
          docker tag ${{ secrets.DOCKER_REPO }}:${{ env.TAG }} ${{ secrets.DOCKER_REPO }}:latest

    - name: Push Version Tag
      run: |
        docker push ${{ secrets.DOCKER_REPO }}:${{ env.TAG }}

    - name: Push Latest Tag (if not beta)
      if: |
        !endsWith(env.TAG, 'b')
      run: |
        docker push ${{ secrets.DOCKER_REPO }}:latest
